yarnPath: .yarn/releases/yarn-4.4.1.cjs

enableGlobalCache: false

defaultSemverRangePrefix: ""

packageExtensions:
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  "@eddeee888/gcg-typescript-resolver-files@*":
    dependencies:
      graphql-scalars: "*"

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  os:
    - win32
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - glibc
