yarnPath: .yarn/releases/yarn-4.4.1.cjs

enableGlobalCache: false

defaultSemverRangePrefix: ""

packageExtensions:
  "@vitejs/plugin-react-swc@*":
    dependencies:
      "@graphql-codegen/client-preset-swc-plugin": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  "@eddeee888/gcg-typescript-resolver-files@*":
    dependencies:
      graphql-scalars: "*"

pnpFallbackMode: all

pnpMode: loose
