yarnPath: .yarn/releases/yarn-4.4.1.cjs

enableGlobalCache: false

defaultSemverRangePrefix: ""

packageExtensions:
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  "@eddeee888/gcg-typescript-resolver-files@*":
    dependencies:
      graphql-scalars: "*"
  drizzle-kit@*:
    dependencies:
      pg: "*"
  drizzle-orm@*:
    dependencies:
      pg: "*"
  "@pixi/react@*":
    dependencies:
      "@pixi/core": "*"
      "@pixi/display": "*"
      "@pixi/math": "*"
      "@pixi/text-bitmap": "*"
      "@pixi/graphics": "*"
      "@pixi/mesh-extras": "*"
      "@pixi/particle-container": "*"
      "@pixi/sprite": "*"
      "@pixi/sprite-animated": "*"
      "@pixi/text": "*"
      "@pixi/sprite-tiling": "*"
      "@pixi/constants": "*"
      "@pixi/app": "*"
      "@pixi/ticker": "*"

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  os:
    - win32
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - glibc
