yarnPath: .yarn/releases/yarn-4.4.1.cjs

enableGlobalCache: false

defaultSemverRangePrefix: ""

packageExtensions:
  "@vitejs/plugin-react-swc@*":
    dependencies:
      "@graphql-codegen/client-preset-swc-plugin": "*"
