apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "space.fullname" . }}-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "space.fullname" . }}-migrations
          image: "{{ .Values.image.repository }}-migrations:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_CONNECTION_STRING
              value: postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ include "space.fullname" . }}-database:5432/{{ .Values.database.name }}
