apiVersion: v1
kind: Service
metadata:
  name: {{ include "space.fullname" . }}-frontend
  labels:
    {{- include "space.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "space.selectorLabelsFrontend" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "space.fullname" . }}-backend
  labels:
    {{- include "space.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "space.selectorLabelsBackend" . | nindent 4 }}
