apiVersion: v1
kind: Service
metadata:
  name: {{ include "space.fullname" . }}-frontend
  labels:
    {{- include "space.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "space.selectorLabelsFrontend" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "space.fullname" . }}-backend
  labels:
    {{- include "space.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "space.selectorLabelsBackend" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "space.fullname" . }}-database
  labels:
    {{- include "space.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: db
      protocol: TCP
      name: db
  selector:
    {{- include "space.selectorLabelsDatabase" . | nindent 4 }}
