/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation RefreshLogin {\n    loginWithRefreshToken {\n      id\n    }\n  }": typeof types.RefreshLoginDocument,
    "mutation CreateGame($name: String!) {\n\t\t\tcreateGame(name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": typeof types.CreateGameDocument,
    "\n      query DilemmaDetails($id: ID!) {\n        dilemma(id: $id) {\n          id\n          title\n          question\n          description\n          choices {\n            id\n            title\n            description\n          }\n          choosen\n          position\n          correlation {\n            ... on StarSystem {\n              id\n              name\n            }\n            ... on Dilemma {\n              id\n              title\n            }\n          }\n        }\n      }\n      ": typeof types.DilemmaDetailsDocument,
    "\n      mutation MakeDilemmaChoice($id: ID!, $choiceId: ID!) {\n        makeDilemmaChoice(dilemmaId: $id, choiceId: $choiceId) {\n          id\n          title\n          choosen\n        }\n      }\n    ": typeof types.MakeDilemmaChoiceDocument,
    "\n\t\t\t\t\t\tquery NextPendingDilemma($gameId: ID!) {\n\t\t\t\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tdilemmas {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tchoosen\n\t\t\t\t\t\t\t\t\tcausation {\n\t\t\t\t\t\t\t\t\t\t... on Dilemma {\n\t\t\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t": typeof types.NextPendingDilemmaDocument,
    "\n\t\t\tquery DilemmasHistoryList($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tquestion\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t\tchoices {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.DilemmasHistoryListDocument,
    "\nquery Galaxy($id: ID!) {\n  game(id: $id) {\n    id\n\t\tstarSystems {\n\t\t\tid\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\ttaskForces {\n\t\t\tid\n\t\t\tname\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\torders {\n\t\t\t\t__typename\n\t\t\t\tid\n\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\tdestination\n\t\t\t\t}\n\t\t\t}\n\t\t\tmovementVector\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\tdilemmas {\n\t\t\tid\n\t\t\ttitle\n\t\t\tquestion\n\t\t\tdescription\n\t\t\tchoices {\n\t\t\t\tid\n\t\t\t\ttitle\n\t\t\t\tdescription\n\t\t\t}\n\t\t\tchoosen\n\t\t\tposition\n\t\t\tcorrelation {\n\t\t\t\t... on StarSystem {\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t}\n\t\t\t\t... on Dilemma {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t}\n\t\t\t}\n\t\t}\n  }\n}": typeof types.GalaxyDocument,
    "mutation OrderTaskForce($id: ID!, $orders: [TaskForceOrderInput!]!, $queue: Boolean) {\n\t\t\torderTaskForce(id: $id, orders: $orders, queue: $queue) {\n\t\t\t\tid\n\t\t\t\torders {\n\t\t\t\t\tid\n\t\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\t\tdestination\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t}": typeof types.OrderTaskForceDocument,
    "subscription TrackMap($gameId: ID!) {\n\t\ttrackGalaxy(gameId: $gameId) {\n\t\t  ... on PositionableApppearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tcolor\n\t\t\t\t\t\t}\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableMovesEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableDisappearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tremoved\n\t\t\t}\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t}\n\t\t\t\t\tsensorRange\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}": typeof types.TrackMapDocument,
    "query GameLobby($id: ID!) {\n      game(id: $id) {\n        id\n        name\n        startedAt\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n        players {\n          id\n          color\n          user {\n            id\n            name\n          }\n        }\n      }\n    }": typeof types.GameLobbyDocument,
    "mutation StartGame($id:ID!) {\n    startGame(id: $id) {\n      id\n      startedAt\n    }\n  }": typeof types.StartGameDocument,
    "mutation UpdatePlayer($gameId: ID!, $input: UpdatePlayerInput!) {\n    updatePlayer(gameId: $gameId, input: $input) {\n      id\n      color\n    }\n  }": typeof types.UpdatePlayerDocument,
    "mutation UpdateGameSettings($gameId: ID!, $input: UpdateGameSettingsInput!) {\n      updateGameSettings(gameId: $gameId, input: $input) {\n        id\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n      }\n    }": typeof types.UpdateGameSettingsDocument,
    "\n\t\t\tquery Games {\n\t\t\t\tgames {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.GamesDocument,
    "\n\t\t\tmutation JoinGame($id: ID!) {\n\t\t\t\tjoinGame(id: $id) {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.JoinGameDocument,
    "\n\t\tquery NotificationCount($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tdilemmas {\n\t\t\t\t\tid\n\t\t\t\t\tchoosen\n\t\t\t\t}\n\t\t\t}\n\t\t}": typeof types.NotificationCountDocument,
    "\n\t\t\tquery CurrentTurnEnded($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnNumber\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t}\n\t\t\t\t\tme {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnEnded\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.CurrentTurnEndedDocument,
    "\n\t\t\tsubscription CurrentTurn($gameId: ID!) {\n\t\t\t\ttrackGame(gameId: $gameId) {\n\t\t\t\t\t__typename\n\t\t\t\t\t... on NewTurnCalculatedEvent {\n\t\t\t\t\t\tgame {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\t\tplayers {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tturnEnded\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.CurrentTurnDocument,
    "\n\t\t\tmutation EndTurn($expectedTurnNumber: Int!, $gameId: ID!) {\n\t\t\t\tendTurn(gameId: $gameId, expectedTurnNumber: $expectedTurnNumber) {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.EndTurnDocument,
    "query ShipComponents($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipComponents {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tcosts { resource { id name } quantity }\n\t\t\t\t\t\tsupplyNeedPassive\n\t\t\t\t\t\tsupplyNeedMovement\n\t\t\t\t\t\tsupplyNeedCombat\n\t\t\t\t\t\tpowerNeed\n\t\t\t\t\t\tcrewNeed\n\t\t\t\t\t\tconstructionCost\n\t\t\t\t\t\tsupplyCapacity\n\t\t\t\t\t\tpowerGeneration\n\t\t\t\t\t\tcrewCapacity\n\t\t\t\t\t\tftlSpeed\n\t\t\t\t\t\tzoneOfControl\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t\tstructuralIntegrity\n\t\t\t\t\t\tthruster\n\t\t\t\t\t\tsensorPrecision\n\t\t\t\t\t\tarmorThickness\n\t\t\t\t\t\tarmorEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tshieldStrength\n\t\t\t\t\t\tshieldEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tweaponDamage\n\t\t\t\t\t\tweaponCooldown\n\t\t\t\t\t\tweaponRange\n\t\t\t\t\t\tweaponArmorPenetration\n\t\t\t\t\t\tweaponShieldPenetration\n\t\t\t\t\t\tweaponAccuracy\n\t\t\t\t\t\tweaponDeliveryType\n\t\t\t\t\t}\n\t\t\t\t\tresources {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": typeof types.ShipComponentsDocument,
    "mutation CreateShipDesign($gameId: ID!, $design: ShipDesignInput!) {\n    createShipDesign(gameId: $gameId, design: $design) {\n      id\n      name\n\t\t\tcosts {\n\t\t\t\tresource {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\t\n\t\t\t\tquantity\n\t\t\t}\n    }\n  }": typeof types.CreateShipDesignDocument,
    "query ShipDesigns($gameId: ID!) {\n    game(id: $gameId) {\n      id\n      me {\n        id\n        shipDesigns {\n          id\n          name\n\t\t\t\t\tcosts {\n\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\t\n\t\t\t\t\t\tquantity\n\t\t\t\t\t}\n        }\n      }\n    }\n  }": typeof types.ShipDesignsDocument,
    "\nmutation SignIn($email:String!, $password:String!) {\n  loginWithPassword(email: $email, password: $password) {\n    id\n    name\n  }\n}": typeof types.SignInDocument,
    "\n    mutation SignIn($email: String!, $password: String!) {\n      loginWithPassword(email: $email, password: $password) {\n        id\n        name\n      }\n    }": typeof types.SignInDocument,
    "\n\t\tmutation SignUp($email: String!, $password: String!, $name:String!) {\n\t\t\tregisterWithPassword(email: $email, password: $password, name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": typeof types.SignUpDocument,
    "query StarSystemDetails($id: ID!) {\n\t\tstarSystem(id: $id) {\n\t\t\tid\n\t\t\tname\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tcolonization {\n\t\t\t\tturnsRemaining\n\t\t\t\tplayer {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tposition\n\t\t\ttaskForces {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\towner {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveries {\n\t\t\t\t__typename\n\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\tid\n\t\t\t\t\tresource {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tremainingDeposits\n\t\t\t\t\tminingRate\n\t\t\t\t}\n\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveryProgress\n\t\t\tpopulations {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t}\n\t\t}\n\t}": typeof types.StarSystemDetailsDocument,
    "query CommissionFleetContext($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipDesigns {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": typeof types.CommissionFleetContextDocument,
    "subscription TrackStarSystem($id: ID!) {\n\t\ttrackStarSystem(starSystemId: $id) {\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tcolonization {\n\t\t\t\t\t\tturnsRemaining\n\t\t\t\t\t\tplayer {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tposition\n\t\t\t\t\ttaskForces {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveries {\n\t\t\t\t\t\t__typename\n\t\t\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tminingRate\n\t\t\t\t\t\t}\n\t\t\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveryProgress\n\t\t\t\t\tpopulations {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tamount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}": typeof types.TrackStarSystemDocument,
    "mutation StartColonization($starSystemId: ID!) {\n\t\t\tstartColonization(starSystemId: $starSystemId) {\n\t\t\t\tid\n\t\t\t\tcolonization {\n\t\t\t\t\tturnsRemaining\n\t\t\t\t\tplayer {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": typeof types.StartColonizationDocument,
    "mutation ConstructTaskForce($input: ConstructTaskForceInput!) {\n\t\t\tconstructTaskForce(input: $input) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": typeof types.ConstructTaskForceDocument,
    "\n\t\t\tquery TurnReportsDetails($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnReports(limit: 40) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tpopulationChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpopulation {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpreviousAmount\n\t\t\t\t\t\t\tnewAmount\n\t\t\t\t\t\t\tgrowth\n\t\t\t\t\t\t}\n\t\t\t\t\t\tminingChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmined\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tdepotQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.TurnReportsDetailsDocument,
    "\n\t\t\tquery CurrentUser {\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\temail\n\t\t\t\t}\n\t\t\t}\n\t\t": typeof types.CurrentUserDocument,
    "\n\t\t\t\t\tmutation RefreshAuth {\n\t\t\t\t\t\tloginWithRefreshToken {\n\t\t\t\t\t\t\t__typename\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}": typeof types.RefreshAuthDocument,
};
const documents: Documents = {
    "mutation RefreshLogin {\n    loginWithRefreshToken {\n      id\n    }\n  }": types.RefreshLoginDocument,
    "mutation CreateGame($name: String!) {\n\t\t\tcreateGame(name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": types.CreateGameDocument,
    "\n      query DilemmaDetails($id: ID!) {\n        dilemma(id: $id) {\n          id\n          title\n          question\n          description\n          choices {\n            id\n            title\n            description\n          }\n          choosen\n          position\n          correlation {\n            ... on StarSystem {\n              id\n              name\n            }\n            ... on Dilemma {\n              id\n              title\n            }\n          }\n        }\n      }\n      ": types.DilemmaDetailsDocument,
    "\n      mutation MakeDilemmaChoice($id: ID!, $choiceId: ID!) {\n        makeDilemmaChoice(dilemmaId: $id, choiceId: $choiceId) {\n          id\n          title\n          choosen\n        }\n      }\n    ": types.MakeDilemmaChoiceDocument,
    "\n\t\t\t\t\t\tquery NextPendingDilemma($gameId: ID!) {\n\t\t\t\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tdilemmas {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tchoosen\n\t\t\t\t\t\t\t\t\tcausation {\n\t\t\t\t\t\t\t\t\t\t... on Dilemma {\n\t\t\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t": types.NextPendingDilemmaDocument,
    "\n\t\t\tquery DilemmasHistoryList($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tquestion\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t\tchoices {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.DilemmasHistoryListDocument,
    "\nquery Galaxy($id: ID!) {\n  game(id: $id) {\n    id\n\t\tstarSystems {\n\t\t\tid\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\ttaskForces {\n\t\t\tid\n\t\t\tname\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\torders {\n\t\t\t\t__typename\n\t\t\t\tid\n\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\tdestination\n\t\t\t\t}\n\t\t\t}\n\t\t\tmovementVector\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\tdilemmas {\n\t\t\tid\n\t\t\ttitle\n\t\t\tquestion\n\t\t\tdescription\n\t\t\tchoices {\n\t\t\t\tid\n\t\t\t\ttitle\n\t\t\t\tdescription\n\t\t\t}\n\t\t\tchoosen\n\t\t\tposition\n\t\t\tcorrelation {\n\t\t\t\t... on StarSystem {\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t}\n\t\t\t\t... on Dilemma {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t}\n\t\t\t}\n\t\t}\n  }\n}": types.GalaxyDocument,
    "mutation OrderTaskForce($id: ID!, $orders: [TaskForceOrderInput!]!, $queue: Boolean) {\n\t\t\torderTaskForce(id: $id, orders: $orders, queue: $queue) {\n\t\t\t\tid\n\t\t\t\torders {\n\t\t\t\t\tid\n\t\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\t\tdestination\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t}": types.OrderTaskForceDocument,
    "subscription TrackMap($gameId: ID!) {\n\t\ttrackGalaxy(gameId: $gameId) {\n\t\t  ... on PositionableApppearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tcolor\n\t\t\t\t\t\t}\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableMovesEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableDisappearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tremoved\n\t\t\t}\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t}\n\t\t\t\t\tsensorRange\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}": types.TrackMapDocument,
    "query GameLobby($id: ID!) {\n      game(id: $id) {\n        id\n        name\n        startedAt\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n        players {\n          id\n          color\n          user {\n            id\n            name\n          }\n        }\n      }\n    }": types.GameLobbyDocument,
    "mutation StartGame($id:ID!) {\n    startGame(id: $id) {\n      id\n      startedAt\n    }\n  }": types.StartGameDocument,
    "mutation UpdatePlayer($gameId: ID!, $input: UpdatePlayerInput!) {\n    updatePlayer(gameId: $gameId, input: $input) {\n      id\n      color\n    }\n  }": types.UpdatePlayerDocument,
    "mutation UpdateGameSettings($gameId: ID!, $input: UpdateGameSettingsInput!) {\n      updateGameSettings(gameId: $gameId, input: $input) {\n        id\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n      }\n    }": types.UpdateGameSettingsDocument,
    "\n\t\t\tquery Games {\n\t\t\t\tgames {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.GamesDocument,
    "\n\t\t\tmutation JoinGame($id: ID!) {\n\t\t\t\tjoinGame(id: $id) {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.JoinGameDocument,
    "\n\t\tquery NotificationCount($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tdilemmas {\n\t\t\t\t\tid\n\t\t\t\t\tchoosen\n\t\t\t\t}\n\t\t\t}\n\t\t}": types.NotificationCountDocument,
    "\n\t\t\tquery CurrentTurnEnded($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnNumber\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t}\n\t\t\t\t\tme {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnEnded\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.CurrentTurnEndedDocument,
    "\n\t\t\tsubscription CurrentTurn($gameId: ID!) {\n\t\t\t\ttrackGame(gameId: $gameId) {\n\t\t\t\t\t__typename\n\t\t\t\t\t... on NewTurnCalculatedEvent {\n\t\t\t\t\t\tgame {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\t\tplayers {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tturnEnded\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.CurrentTurnDocument,
    "\n\t\t\tmutation EndTurn($expectedTurnNumber: Int!, $gameId: ID!) {\n\t\t\t\tendTurn(gameId: $gameId, expectedTurnNumber: $expectedTurnNumber) {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t": types.EndTurnDocument,
    "query ShipComponents($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipComponents {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tcosts { resource { id name } quantity }\n\t\t\t\t\t\tsupplyNeedPassive\n\t\t\t\t\t\tsupplyNeedMovement\n\t\t\t\t\t\tsupplyNeedCombat\n\t\t\t\t\t\tpowerNeed\n\t\t\t\t\t\tcrewNeed\n\t\t\t\t\t\tconstructionCost\n\t\t\t\t\t\tsupplyCapacity\n\t\t\t\t\t\tpowerGeneration\n\t\t\t\t\t\tcrewCapacity\n\t\t\t\t\t\tftlSpeed\n\t\t\t\t\t\tzoneOfControl\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t\tstructuralIntegrity\n\t\t\t\t\t\tthruster\n\t\t\t\t\t\tsensorPrecision\n\t\t\t\t\t\tarmorThickness\n\t\t\t\t\t\tarmorEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tshieldStrength\n\t\t\t\t\t\tshieldEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tweaponDamage\n\t\t\t\t\t\tweaponCooldown\n\t\t\t\t\t\tweaponRange\n\t\t\t\t\t\tweaponArmorPenetration\n\t\t\t\t\t\tweaponShieldPenetration\n\t\t\t\t\t\tweaponAccuracy\n\t\t\t\t\t\tweaponDeliveryType\n\t\t\t\t\t}\n\t\t\t\t\tresources {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": types.ShipComponentsDocument,
    "mutation CreateShipDesign($gameId: ID!, $design: ShipDesignInput!) {\n    createShipDesign(gameId: $gameId, design: $design) {\n      id\n      name\n\t\t\tcosts {\n\t\t\t\tresource {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\t\n\t\t\t\tquantity\n\t\t\t}\n    }\n  }": types.CreateShipDesignDocument,
    "query ShipDesigns($gameId: ID!) {\n    game(id: $gameId) {\n      id\n      me {\n        id\n        shipDesigns {\n          id\n          name\n\t\t\t\t\tcosts {\n\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\t\n\t\t\t\t\t\tquantity\n\t\t\t\t\t}\n        }\n      }\n    }\n  }": types.ShipDesignsDocument,
    "\nmutation SignIn($email:String!, $password:String!) {\n  loginWithPassword(email: $email, password: $password) {\n    id\n    name\n  }\n}": types.SignInDocument,
    "\n    mutation SignIn($email: String!, $password: String!) {\n      loginWithPassword(email: $email, password: $password) {\n        id\n        name\n      }\n    }": types.SignInDocument,
    "\n\t\tmutation SignUp($email: String!, $password: String!, $name:String!) {\n\t\t\tregisterWithPassword(email: $email, password: $password, name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": types.SignUpDocument,
    "query StarSystemDetails($id: ID!) {\n\t\tstarSystem(id: $id) {\n\t\t\tid\n\t\t\tname\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tcolonization {\n\t\t\t\tturnsRemaining\n\t\t\t\tplayer {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tposition\n\t\t\ttaskForces {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\towner {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveries {\n\t\t\t\t__typename\n\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\tid\n\t\t\t\t\tresource {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tremainingDeposits\n\t\t\t\t\tminingRate\n\t\t\t\t}\n\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveryProgress\n\t\t\tpopulations {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t}\n\t\t}\n\t}": types.StarSystemDetailsDocument,
    "query CommissionFleetContext($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipDesigns {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": types.CommissionFleetContextDocument,
    "subscription TrackStarSystem($id: ID!) {\n\t\ttrackStarSystem(starSystemId: $id) {\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tcolonization {\n\t\t\t\t\t\tturnsRemaining\n\t\t\t\t\t\tplayer {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tposition\n\t\t\t\t\ttaskForces {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveries {\n\t\t\t\t\t\t__typename\n\t\t\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tminingRate\n\t\t\t\t\t\t}\n\t\t\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveryProgress\n\t\t\t\t\tpopulations {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tamount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}": types.TrackStarSystemDocument,
    "mutation StartColonization($starSystemId: ID!) {\n\t\t\tstartColonization(starSystemId: $starSystemId) {\n\t\t\t\tid\n\t\t\t\tcolonization {\n\t\t\t\t\tturnsRemaining\n\t\t\t\t\tplayer {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}": types.StartColonizationDocument,
    "mutation ConstructTaskForce($input: ConstructTaskForceInput!) {\n\t\t\tconstructTaskForce(input: $input) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}": types.ConstructTaskForceDocument,
    "\n\t\t\tquery TurnReportsDetails($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnReports(limit: 40) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tpopulationChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpopulation {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpreviousAmount\n\t\t\t\t\t\t\tnewAmount\n\t\t\t\t\t\t\tgrowth\n\t\t\t\t\t\t}\n\t\t\t\t\t\tminingChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmined\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tdepotQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t": types.TurnReportsDetailsDocument,
    "\n\t\t\tquery CurrentUser {\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\temail\n\t\t\t\t}\n\t\t\t}\n\t\t": types.CurrentUserDocument,
    "\n\t\t\t\t\tmutation RefreshAuth {\n\t\t\t\t\t\tloginWithRefreshToken {\n\t\t\t\t\t\t\t__typename\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}": types.RefreshAuthDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation RefreshLogin {\n    loginWithRefreshToken {\n      id\n    }\n  }"): (typeof documents)["mutation RefreshLogin {\n    loginWithRefreshToken {\n      id\n    }\n  }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateGame($name: String!) {\n\t\t\tcreateGame(name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"): (typeof documents)["mutation CreateGame($name: String!) {\n\t\t\tcreateGame(name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query DilemmaDetails($id: ID!) {\n        dilemma(id: $id) {\n          id\n          title\n          question\n          description\n          choices {\n            id\n            title\n            description\n          }\n          choosen\n          position\n          correlation {\n            ... on StarSystem {\n              id\n              name\n            }\n            ... on Dilemma {\n              id\n              title\n            }\n          }\n        }\n      }\n      "): (typeof documents)["\n      query DilemmaDetails($id: ID!) {\n        dilemma(id: $id) {\n          id\n          title\n          question\n          description\n          choices {\n            id\n            title\n            description\n          }\n          choosen\n          position\n          correlation {\n            ... on StarSystem {\n              id\n              name\n            }\n            ... on Dilemma {\n              id\n              title\n            }\n          }\n        }\n      }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation MakeDilemmaChoice($id: ID!, $choiceId: ID!) {\n        makeDilemmaChoice(dilemmaId: $id, choiceId: $choiceId) {\n          id\n          title\n          choosen\n        }\n      }\n    "): (typeof documents)["\n      mutation MakeDilemmaChoice($id: ID!, $choiceId: ID!) {\n        makeDilemmaChoice(dilemmaId: $id, choiceId: $choiceId) {\n          id\n          title\n          choosen\n        }\n      }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\t\t\tquery NextPendingDilemma($gameId: ID!) {\n\t\t\t\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tdilemmas {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tchoosen\n\t\t\t\t\t\t\t\t\tcausation {\n\t\t\t\t\t\t\t\t\t\t... on Dilemma {\n\t\t\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t"): (typeof documents)["\n\t\t\t\t\t\tquery NextPendingDilemma($gameId: ID!) {\n\t\t\t\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tdilemmas {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tchoosen\n\t\t\t\t\t\t\t\t\tcausation {\n\t\t\t\t\t\t\t\t\t\t... on Dilemma {\n\t\t\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tquery DilemmasHistoryList($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tquestion\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t\tchoices {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tquery DilemmasHistoryList($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttitle\n\t\t\t\t\t\tquestion\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t\tchoices {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\nquery Galaxy($id: ID!) {\n  game(id: $id) {\n    id\n\t\tstarSystems {\n\t\t\tid\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\ttaskForces {\n\t\t\tid\n\t\t\tname\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\torders {\n\t\t\t\t__typename\n\t\t\t\tid\n\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\tdestination\n\t\t\t\t}\n\t\t\t}\n\t\t\tmovementVector\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\tdilemmas {\n\t\t\tid\n\t\t\ttitle\n\t\t\tquestion\n\t\t\tdescription\n\t\t\tchoices {\n\t\t\t\tid\n\t\t\t\ttitle\n\t\t\t\tdescription\n\t\t\t}\n\t\t\tchoosen\n\t\t\tposition\n\t\t\tcorrelation {\n\t\t\t\t... on StarSystem {\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t}\n\t\t\t\t... on Dilemma {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t}\n\t\t\t}\n\t\t}\n  }\n}"): (typeof documents)["\nquery Galaxy($id: ID!) {\n  game(id: $id) {\n    id\n\t\tstarSystems {\n\t\t\tid\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\ttaskForces {\n\t\t\tid\n\t\t\tname\n\t\t\tposition\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcolor\n\t\t\t}\n\t\t\torders {\n\t\t\t\t__typename\n\t\t\t\tid\n\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\tdestination\n\t\t\t\t}\n\t\t\t}\n\t\t\tmovementVector\n\t\t\tisVisible\n\t\t\tlastUpdate\n\t\t\tsensorRange\n\t\t}\n\t\tdilemmas {\n\t\t\tid\n\t\t\ttitle\n\t\t\tquestion\n\t\t\tdescription\n\t\t\tchoices {\n\t\t\t\tid\n\t\t\t\ttitle\n\t\t\t\tdescription\n\t\t\t}\n\t\t\tchoosen\n\t\t\tposition\n\t\t\tcorrelation {\n\t\t\t\t... on StarSystem {\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t}\n\t\t\t\t... on Dilemma {\n\t\t\t\t\tid\n\t\t\t\t\ttitle\n\t\t\t\t}\n\t\t\t}\n\t\t}\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation OrderTaskForce($id: ID!, $orders: [TaskForceOrderInput!]!, $queue: Boolean) {\n\t\t\torderTaskForce(id: $id, orders: $orders, queue: $queue) {\n\t\t\t\tid\n\t\t\t\torders {\n\t\t\t\t\tid\n\t\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\t\tdestination\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t}"): (typeof documents)["mutation OrderTaskForce($id: ID!, $orders: [TaskForceOrderInput!]!, $queue: Boolean) {\n\t\t\torderTaskForce(id: $id, orders: $orders, queue: $queue) {\n\t\t\t\tid\n\t\t\t\torders {\n\t\t\t\t\tid\n\t\t\t\t\t...on TaskForceMoveOrder {\n\t\t\t\t\t\tdestination\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription TrackMap($gameId: ID!) {\n\t\ttrackGalaxy(gameId: $gameId) {\n\t\t  ... on PositionableApppearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tcolor\n\t\t\t\t\t\t}\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableMovesEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableDisappearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tremoved\n\t\t\t}\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t}\n\t\t\t\t\tsensorRange\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}"): (typeof documents)["subscription TrackMap($gameId: ID!) {\n\t\ttrackGalaxy(gameId: $gameId) {\n\t\t  ... on PositionableApppearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tcolor\n\t\t\t\t\t\t}\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableMovesEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tmovementVector\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t  ... on PositionableDisappearsEvent {\n\t\t\t\tsubject {\n\t\t\t\t\t__typename\n\t\t\t\t\tid\n\t\t\t\t\tposition\n\t\t\t\t\t... on TaskForce {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t}\n\t\t\t\t\t... on StarSystem {\n\t\t\t\t\t\tisVisible\n\t\t\t\t\t\tlastUpdate\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tremoved\n\t\t\t}\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t}\n\t\t\t\t\tsensorRange\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GameLobby($id: ID!) {\n      game(id: $id) {\n        id\n        name\n        startedAt\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n        players {\n          id\n          color\n          user {\n            id\n            name\n          }\n        }\n      }\n    }"): (typeof documents)["query GameLobby($id: ID!) {\n      game(id: $id) {\n        id\n        name\n        startedAt\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n        players {\n          id\n          color\n          user {\n            id\n            name\n          }\n        }\n      }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation StartGame($id:ID!) {\n    startGame(id: $id) {\n      id\n      startedAt\n    }\n  }"): (typeof documents)["mutation StartGame($id:ID!) {\n    startGame(id: $id) {\n      id\n      startedAt\n    }\n  }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdatePlayer($gameId: ID!, $input: UpdatePlayerInput!) {\n    updatePlayer(gameId: $gameId, input: $input) {\n      id\n      color\n    }\n  }"): (typeof documents)["mutation UpdatePlayer($gameId: ID!, $input: UpdatePlayerInput!) {\n    updatePlayer(gameId: $gameId, input: $input) {\n      id\n      color\n    }\n  }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateGameSettings($gameId: ID!, $input: UpdateGameSettingsInput!) {\n      updateGameSettings(gameId: $gameId, input: $input) {\n        id\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n      }\n    }"): (typeof documents)["mutation UpdateGameSettings($gameId: ID!, $input: UpdateGameSettingsInput!) {\n      updateGameSettings(gameId: $gameId, input: $input) {\n        id\n        autoEndTurnAfterHoursInactive\n        autoEndTurnEveryHours\n      }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tquery Games {\n\t\t\t\tgames {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tquery Games {\n\t\t\t\tgames {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tmutation JoinGame($id: ID!) {\n\t\t\t\tjoinGame(id: $id) {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tmutation JoinGame($id: ID!) {\n\t\t\t\tjoinGame(id: $id) {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tstartedAt\n\t\t\t\t\tplayers {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcolor\n\t\t\t\t\t\tuser {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\tquery NotificationCount($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tdilemmas {\n\t\t\t\t\tid\n\t\t\t\t\tchoosen\n\t\t\t\t}\n\t\t\t}\n\t\t}"): (typeof documents)["\n\t\tquery NotificationCount($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tdilemmas {\n\t\t\t\t\tid\n\t\t\t\t\tchoosen\n\t\t\t\t}\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tquery CurrentTurnEnded($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnNumber\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t}\n\t\t\t\t\tme {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnEnded\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tquery CurrentTurnEnded($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnNumber\n\t\t\t\t\tdilemmas {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tchoosen\n\t\t\t\t\t}\n\t\t\t\t\tme {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnEnded\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tsubscription CurrentTurn($gameId: ID!) {\n\t\t\t\ttrackGame(gameId: $gameId) {\n\t\t\t\t\t__typename\n\t\t\t\t\t... on NewTurnCalculatedEvent {\n\t\t\t\t\t\tgame {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\t\tplayers {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tturnEnded\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tsubscription CurrentTurn($gameId: ID!) {\n\t\t\t\ttrackGame(gameId: $gameId) {\n\t\t\t\t\t__typename\n\t\t\t\t\t... on NewTurnCalculatedEvent {\n\t\t\t\t\t\tgame {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\t\tplayers {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tturnEnded\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tmutation EndTurn($expectedTurnNumber: Int!, $gameId: ID!) {\n\t\t\t\tendTurn(gameId: $gameId, expectedTurnNumber: $expectedTurnNumber) {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tmutation EndTurn($expectedTurnNumber: Int!, $gameId: ID!) {\n\t\t\t\tendTurn(gameId: $gameId, expectedTurnNumber: $expectedTurnNumber) {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ShipComponents($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipComponents {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tcosts { resource { id name } quantity }\n\t\t\t\t\t\tsupplyNeedPassive\n\t\t\t\t\t\tsupplyNeedMovement\n\t\t\t\t\t\tsupplyNeedCombat\n\t\t\t\t\t\tpowerNeed\n\t\t\t\t\t\tcrewNeed\n\t\t\t\t\t\tconstructionCost\n\t\t\t\t\t\tsupplyCapacity\n\t\t\t\t\t\tpowerGeneration\n\t\t\t\t\t\tcrewCapacity\n\t\t\t\t\t\tftlSpeed\n\t\t\t\t\t\tzoneOfControl\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t\tstructuralIntegrity\n\t\t\t\t\t\tthruster\n\t\t\t\t\t\tsensorPrecision\n\t\t\t\t\t\tarmorThickness\n\t\t\t\t\t\tarmorEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tshieldStrength\n\t\t\t\t\t\tshieldEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tweaponDamage\n\t\t\t\t\t\tweaponCooldown\n\t\t\t\t\t\tweaponRange\n\t\t\t\t\t\tweaponArmorPenetration\n\t\t\t\t\t\tweaponShieldPenetration\n\t\t\t\t\t\tweaponAccuracy\n\t\t\t\t\t\tweaponDeliveryType\n\t\t\t\t\t}\n\t\t\t\t\tresources {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"): (typeof documents)["query ShipComponents($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipComponents {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tcosts { resource { id name } quantity }\n\t\t\t\t\t\tsupplyNeedPassive\n\t\t\t\t\t\tsupplyNeedMovement\n\t\t\t\t\t\tsupplyNeedCombat\n\t\t\t\t\t\tpowerNeed\n\t\t\t\t\t\tcrewNeed\n\t\t\t\t\t\tconstructionCost\n\t\t\t\t\t\tsupplyCapacity\n\t\t\t\t\t\tpowerGeneration\n\t\t\t\t\t\tcrewCapacity\n\t\t\t\t\t\tftlSpeed\n\t\t\t\t\t\tzoneOfControl\n\t\t\t\t\t\tsensorRange\n\t\t\t\t\t\tstructuralIntegrity\n\t\t\t\t\t\tthruster\n\t\t\t\t\t\tsensorPrecision\n\t\t\t\t\t\tarmorThickness\n\t\t\t\t\t\tarmorEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tshieldStrength\n\t\t\t\t\t\tshieldEffectivenessAgainst { projectile missile beam instant }\n\t\t\t\t\t\tweaponDamage\n\t\t\t\t\t\tweaponCooldown\n\t\t\t\t\t\tweaponRange\n\t\t\t\t\t\tweaponArmorPenetration\n\t\t\t\t\t\tweaponShieldPenetration\n\t\t\t\t\t\tweaponAccuracy\n\t\t\t\t\t\tweaponDeliveryType\n\t\t\t\t\t}\n\t\t\t\t\tresources {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateShipDesign($gameId: ID!, $design: ShipDesignInput!) {\n    createShipDesign(gameId: $gameId, design: $design) {\n      id\n      name\n\t\t\tcosts {\n\t\t\t\tresource {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\t\n\t\t\t\tquantity\n\t\t\t}\n    }\n  }"): (typeof documents)["mutation CreateShipDesign($gameId: ID!, $design: ShipDesignInput!) {\n    createShipDesign(gameId: $gameId, design: $design) {\n      id\n      name\n\t\t\tcosts {\n\t\t\t\tresource {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\t\n\t\t\t\tquantity\n\t\t\t}\n    }\n  }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ShipDesigns($gameId: ID!) {\n    game(id: $gameId) {\n      id\n      me {\n        id\n        shipDesigns {\n          id\n          name\n\t\t\t\t\tcosts {\n\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\t\n\t\t\t\t\t\tquantity\n\t\t\t\t\t}\n        }\n      }\n    }\n  }"): (typeof documents)["query ShipDesigns($gameId: ID!) {\n    game(id: $gameId) {\n      id\n      me {\n        id\n        shipDesigns {\n          id\n          name\n\t\t\t\t\tcosts {\n\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\t\n\t\t\t\t\t\tquantity\n\t\t\t\t\t}\n        }\n      }\n    }\n  }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\nmutation SignIn($email:String!, $password:String!) {\n  loginWithPassword(email: $email, password: $password) {\n    id\n    name\n  }\n}"): (typeof documents)["\nmutation SignIn($email:String!, $password:String!) {\n  loginWithPassword(email: $email, password: $password) {\n    id\n    name\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SignIn($email: String!, $password: String!) {\n      loginWithPassword(email: $email, password: $password) {\n        id\n        name\n      }\n    }"): (typeof documents)["\n    mutation SignIn($email: String!, $password: String!) {\n      loginWithPassword(email: $email, password: $password) {\n        id\n        name\n      }\n    }"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\tmutation SignUp($email: String!, $password: String!, $name:String!) {\n\t\t\tregisterWithPassword(email: $email, password: $password, name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"): (typeof documents)["\n\t\tmutation SignUp($email: String!, $password: String!, $name:String!) {\n\t\t\tregisterWithPassword(email: $email, password: $password, name: $name) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query StarSystemDetails($id: ID!) {\n\t\tstarSystem(id: $id) {\n\t\t\tid\n\t\t\tname\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tcolonization {\n\t\t\t\tturnsRemaining\n\t\t\t\tplayer {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tposition\n\t\t\ttaskForces {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\towner {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveries {\n\t\t\t\t__typename\n\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\tid\n\t\t\t\t\tresource {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tremainingDeposits\n\t\t\t\t\tminingRate\n\t\t\t\t}\n\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveryProgress\n\t\t\tpopulations {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t}\n\t\t}\n\t}"): (typeof documents)["query StarSystemDetails($id: ID!) {\n\t\tstarSystem(id: $id) {\n\t\t\tid\n\t\t\tname\n\t\t\towner {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tcolonization {\n\t\t\t\tturnsRemaining\n\t\t\t\tplayer {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tposition\n\t\t\ttaskForces {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\towner {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveries {\n\t\t\t\t__typename\n\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\tid\n\t\t\t\t\tresource {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tremainingDeposits\n\t\t\t\t\tminingRate\n\t\t\t\t}\n\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\tid\n\t\t\t\t}\n\t\t\t}\n\t\t\tdiscoveryProgress\n\t\t\tpopulations {\n\t\t\t\tid\n\t\t\t\tamount\n\t\t\t}\n\t\t}\n\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CommissionFleetContext($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipDesigns {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"): (typeof documents)["query CommissionFleetContext($gameId: ID!) {\n\t\t\tgame(id: $gameId) {\n\t\t\t\tid\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tshipDesigns {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription TrackStarSystem($id: ID!) {\n\t\ttrackStarSystem(starSystemId: $id) {\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tcolonization {\n\t\t\t\t\t\tturnsRemaining\n\t\t\t\t\t\tplayer {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tposition\n\t\t\t\t\ttaskForces {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveries {\n\t\t\t\t\t\t__typename\n\t\t\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tminingRate\n\t\t\t\t\t\t}\n\t\t\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveryProgress\n\t\t\t\t\tpopulations {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tamount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}"): (typeof documents)["subscription TrackStarSystem($id: ID!) {\n\t\ttrackStarSystem(starSystemId: $id) {\n\t\t\t... on StarSystemUpdateEvent {\n\t\t\t\tsubject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\towner {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t\tcolonization {\n\t\t\t\t\t\tturnsRemaining\n\t\t\t\t\t\tplayer {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tposition\n\t\t\t\t\ttaskForces {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\towner {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveries {\n\t\t\t\t\t\t__typename\n\t\t\t\t\t\t... on ResourceDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tminingRate\n\t\t\t\t\t\t}\n\t\t\t\t\t\t... on UnknownDiscovery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t\tdiscoveryProgress\n\t\t\t\t\tpopulations {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tamount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation StartColonization($starSystemId: ID!) {\n\t\t\tstartColonization(starSystemId: $starSystemId) {\n\t\t\t\tid\n\t\t\t\tcolonization {\n\t\t\t\t\tturnsRemaining\n\t\t\t\t\tplayer {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"): (typeof documents)["mutation StartColonization($starSystemId: ID!) {\n\t\t\tstartColonization(starSystemId: $starSystemId) {\n\t\t\t\tid\n\t\t\t\tcolonization {\n\t\t\t\t\tturnsRemaining\n\t\t\t\t\tplayer {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation ConstructTaskForce($input: ConstructTaskForceInput!) {\n\t\t\tconstructTaskForce(input: $input) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"): (typeof documents)["mutation ConstructTaskForce($input: ConstructTaskForceInput!) {\n\t\t\tconstructTaskForce(input: $input) {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tquery TurnReportsDetails($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnReports(limit: 40) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tpopulationChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpopulation {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpreviousAmount\n\t\t\t\t\t\t\tnewAmount\n\t\t\t\t\t\t\tgrowth\n\t\t\t\t\t\t}\n\t\t\t\t\t\tminingChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmined\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tdepotQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tquery TurnReportsDetails($gameId: ID!) {\n\t\t\t\tgame(id: $gameId) {\n\t\t\t\t\tid\n\t\t\t\t\tturnReports(limit: 40) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tturnNumber\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tpopulationChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpopulation {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpreviousAmount\n\t\t\t\t\t\t\tnewAmount\n\t\t\t\t\t\t\tgrowth\n\t\t\t\t\t\t}\n\t\t\t\t\t\tminingChanges {\n\t\t\t\t\t\t\tstarSystem {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tresource {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmined\n\t\t\t\t\t\t\tremainingDeposits\n\t\t\t\t\t\t\tdepotQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\tquery CurrentUser {\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\temail\n\t\t\t\t}\n\t\t\t}\n\t\t"): (typeof documents)["\n\t\t\tquery CurrentUser {\n\t\t\t\tme {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\temail\n\t\t\t\t}\n\t\t\t}\n\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\t\tmutation RefreshAuth {\n\t\t\t\t\t\tloginWithRefreshToken {\n\t\t\t\t\t\t\t__typename\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}"): (typeof documents)["\n\t\t\t\t\tmutation RefreshAuth {\n\t\t\t\t\t\tloginWithRefreshToken {\n\t\t\t\t\t\t\t__typename\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;