/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as GamesAuthenticatedRouteImport } from './routes/games/_authenticated'
import { Route as DashboardSigninRouteImport } from './routes/_dashboard/signin'
import { Route as DashboardLearnRouteImport } from './routes/_dashboard/learn'
import { Route as DashboardFeaturesRouteImport } from './routes/_dashboard/features'
import { Route as DashboardAuthenticatedRouteImport } from './routes/_dashboard/_authenticated'
import { Route as DashboardAuthenticatedGamesIndexRouteImport } from './routes/_dashboard/_authenticated.games/index'
import { Route as DashboardAuthenticatedGamesLobbyIdRouteImport } from './routes/_dashboard/_authenticated.games/lobby.$id'

const GamesRouteImport = createFileRoute('/games')()
const GamesAuthenticatedIdLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id',
)()
const GamesAuthenticatedIdTurnReportsLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id/turn-reports',
)()
const GamesAuthenticatedIdShipDesignsLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id/ship-designs',
)()
const GamesAuthenticatedIdDilemmasIndexLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id/dilemmas/',
)()
const GamesAuthenticatedIdStarSystemStarSystemIdLazyRouteImport =
  createFileRoute('/games/_authenticated/$id/star-system/$starSystemId')()
const GamesAuthenticatedIdShipDesignsNewLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id/ship-designs/new',
)()
const GamesAuthenticatedIdEngagementEngagementIdLazyRouteImport =
  createFileRoute('/games/_authenticated/$id/engagement/$engagementId')()
const GamesAuthenticatedIdDilemmasDilemmaIdLazyRouteImport = createFileRoute(
  '/games/_authenticated/$id/dilemmas/$dilemmaId',
)()

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GamesAuthenticatedRoute = GamesAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => GamesRoute,
} as any)
const DashboardSigninRoute = DashboardSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearnRoute = DashboardLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeaturesRoute = DashboardFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthenticatedRoute = DashboardAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => DashboardRoute,
} as any)
const GamesAuthenticatedIdLazyRoute =
  GamesAuthenticatedIdLazyRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => GamesAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id.lazy').then((d) => d.Route),
  )
const DashboardAuthenticatedGamesIndexRoute =
  DashboardAuthenticatedGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => DashboardAuthenticatedRoute,
  } as any)
const GamesAuthenticatedIdTurnReportsLazyRoute =
  GamesAuthenticatedIdTurnReportsLazyRouteImport.update({
    id: '/turn-reports',
    path: '/turn-reports',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id/turn-reports.lazy').then(
      (d) => d.Route,
    ),
  )
const GamesAuthenticatedIdShipDesignsLazyRoute =
  GamesAuthenticatedIdShipDesignsLazyRouteImport.update({
    id: '/ship-designs',
    path: '/ship-designs',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id/ship-designs.lazy').then(
      (d) => d.Route,
    ),
  )
const GamesAuthenticatedIdDilemmasIndexLazyRoute =
  GamesAuthenticatedIdDilemmasIndexLazyRouteImport.update({
    id: '/dilemmas/',
    path: '/dilemmas/',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id/dilemmas.index.lazy').then(
      (d) => d.Route,
    ),
  )
const GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute =
  GamesAuthenticatedIdStarSystemStarSystemIdLazyRouteImport.update({
    id: '/star-system/$starSystemId',
    path: '/star-system/$starSystemId',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/games/_authenticated.$id/star-system.$starSystemId.lazy'
    ).then((d) => d.Route),
  )
const GamesAuthenticatedIdShipDesignsNewLazyRoute =
  GamesAuthenticatedIdShipDesignsNewLazyRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => GamesAuthenticatedIdShipDesignsLazyRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id/ship-designs.new.lazy').then(
      (d) => d.Route,
    ),
  )
const GamesAuthenticatedIdEngagementEngagementIdLazyRoute =
  GamesAuthenticatedIdEngagementEngagementIdLazyRouteImport.update({
    id: '/engagement/$engagementId',
    path: '/engagement/$engagementId',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/games/_authenticated.$id/engagement.$engagementId.lazy'
    ).then((d) => d.Route),
  )
const GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute =
  GamesAuthenticatedIdDilemmasDilemmaIdLazyRouteImport.update({
    id: '/dilemmas/$dilemmaId',
    path: '/dilemmas/$dilemmaId',
    getParentRoute: () => GamesAuthenticatedIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/games/_authenticated.$id/dilemmas.$dilemmaId.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardAuthenticatedGamesLobbyIdRoute =
  DashboardAuthenticatedGamesLobbyIdRouteImport.update({
    id: '/games/lobby/$id',
    path: '/games/lobby/$id',
    getParentRoute: () => DashboardAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/features': typeof DashboardFeaturesRoute
  '/learn': typeof DashboardLearnRoute
  '/signin': typeof DashboardSigninRoute
  '/games': typeof DashboardAuthenticatedGamesIndexRoute
  '/': typeof DashboardIndexRoute
  '/games/$id': typeof GamesAuthenticatedIdLazyRouteWithChildren
  '/games/$id/ship-designs': typeof GamesAuthenticatedIdShipDesignsLazyRouteWithChildren
  '/games/$id/turn-reports': typeof GamesAuthenticatedIdTurnReportsLazyRoute
  '/games/lobby/$id': typeof DashboardAuthenticatedGamesLobbyIdRoute
  '/games/$id/dilemmas/$dilemmaId': typeof GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute
  '/games/$id/engagement/$engagementId': typeof GamesAuthenticatedIdEngagementEngagementIdLazyRoute
  '/games/$id/ship-designs/new': typeof GamesAuthenticatedIdShipDesignsNewLazyRoute
  '/games/$id/star-system/$starSystemId': typeof GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute
  '/games/$id/dilemmas': typeof GamesAuthenticatedIdDilemmasIndexLazyRoute
}
export interface FileRoutesByTo {
  '/features': typeof DashboardFeaturesRoute
  '/learn': typeof DashboardLearnRoute
  '/signin': typeof DashboardSigninRoute
  '/games': typeof DashboardAuthenticatedGamesIndexRoute
  '/': typeof DashboardIndexRoute
  '/games/$id': typeof GamesAuthenticatedIdLazyRouteWithChildren
  '/games/$id/ship-designs': typeof GamesAuthenticatedIdShipDesignsLazyRouteWithChildren
  '/games/$id/turn-reports': typeof GamesAuthenticatedIdTurnReportsLazyRoute
  '/games/lobby/$id': typeof DashboardAuthenticatedGamesLobbyIdRoute
  '/games/$id/dilemmas/$dilemmaId': typeof GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute
  '/games/$id/engagement/$engagementId': typeof GamesAuthenticatedIdEngagementEngagementIdLazyRoute
  '/games/$id/ship-designs/new': typeof GamesAuthenticatedIdShipDesignsNewLazyRoute
  '/games/$id/star-system/$starSystemId': typeof GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute
  '/games/$id/dilemmas': typeof GamesAuthenticatedIdDilemmasIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/_authenticated': typeof DashboardAuthenticatedRouteWithChildren
  '/_dashboard/features': typeof DashboardFeaturesRoute
  '/_dashboard/learn': typeof DashboardLearnRoute
  '/_dashboard/signin': typeof DashboardSigninRoute
  '/games': typeof GamesRouteWithChildren
  '/games/_authenticated': typeof GamesAuthenticatedRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/games/_authenticated/$id': typeof GamesAuthenticatedIdLazyRouteWithChildren
  '/games/_authenticated/$id/ship-designs': typeof GamesAuthenticatedIdShipDesignsLazyRouteWithChildren
  '/games/_authenticated/$id/turn-reports': typeof GamesAuthenticatedIdTurnReportsLazyRoute
  '/_dashboard/_authenticated/games/': typeof DashboardAuthenticatedGamesIndexRoute
  '/_dashboard/_authenticated/games/lobby/$id': typeof DashboardAuthenticatedGamesLobbyIdRoute
  '/games/_authenticated/$id/dilemmas/$dilemmaId': typeof GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute
  '/games/_authenticated/$id/engagement/$engagementId': typeof GamesAuthenticatedIdEngagementEngagementIdLazyRoute
  '/games/_authenticated/$id/ship-designs/new': typeof GamesAuthenticatedIdShipDesignsNewLazyRoute
  '/games/_authenticated/$id/star-system/$starSystemId': typeof GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute
  '/games/_authenticated/$id/dilemmas/': typeof GamesAuthenticatedIdDilemmasIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/features'
    | '/learn'
    | '/signin'
    | '/games'
    | '/'
    | '/games/$id'
    | '/games/$id/ship-designs'
    | '/games/$id/turn-reports'
    | '/games/lobby/$id'
    | '/games/$id/dilemmas/$dilemmaId'
    | '/games/$id/engagement/$engagementId'
    | '/games/$id/ship-designs/new'
    | '/games/$id/star-system/$starSystemId'
    | '/games/$id/dilemmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/features'
    | '/learn'
    | '/signin'
    | '/games'
    | '/'
    | '/games/$id'
    | '/games/$id/ship-designs'
    | '/games/$id/turn-reports'
    | '/games/lobby/$id'
    | '/games/$id/dilemmas/$dilemmaId'
    | '/games/$id/engagement/$engagementId'
    | '/games/$id/ship-designs/new'
    | '/games/$id/star-system/$starSystemId'
    | '/games/$id/dilemmas'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/_authenticated'
    | '/_dashboard/features'
    | '/_dashboard/learn'
    | '/_dashboard/signin'
    | '/games'
    | '/games/_authenticated'
    | '/_dashboard/'
    | '/games/_authenticated/$id'
    | '/games/_authenticated/$id/ship-designs'
    | '/games/_authenticated/$id/turn-reports'
    | '/_dashboard/_authenticated/games/'
    | '/_dashboard/_authenticated/games/lobby/$id'
    | '/games/_authenticated/$id/dilemmas/$dilemmaId'
    | '/games/_authenticated/$id/engagement/$engagementId'
    | '/games/_authenticated/$id/ship-designs/new'
    | '/games/_authenticated/$id/star-system/$starSystemId'
    | '/games/_authenticated/$id/dilemmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/games/_authenticated': {
      id: '/games/_authenticated'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesAuthenticatedRouteImport
      parentRoute: typeof GamesRoute
    }
    '/_dashboard/signin': {
      id: '/_dashboard/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof DashboardSigninRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/learn': {
      id: '/_dashboard/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof DashboardLearnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/features': {
      id: '/_dashboard/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof DashboardFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_authenticated': {
      id: '/_dashboard/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardAuthenticatedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/games/_authenticated/$id': {
      id: '/games/_authenticated/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesAuthenticatedIdLazyRouteImport
      parentRoute: typeof GamesAuthenticatedRoute
    }
    '/_dashboard/_authenticated/games/': {
      id: '/_dashboard/_authenticated/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof DashboardAuthenticatedGamesIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRoute
    }
    '/games/_authenticated/$id/turn-reports': {
      id: '/games/_authenticated/$id/turn-reports'
      path: '/turn-reports'
      fullPath: '/games/$id/turn-reports'
      preLoaderRoute: typeof GamesAuthenticatedIdTurnReportsLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/games/_authenticated/$id/ship-designs': {
      id: '/games/_authenticated/$id/ship-designs'
      path: '/ship-designs'
      fullPath: '/games/$id/ship-designs'
      preLoaderRoute: typeof GamesAuthenticatedIdShipDesignsLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/games/_authenticated/$id/dilemmas/': {
      id: '/games/_authenticated/$id/dilemmas/'
      path: '/dilemmas'
      fullPath: '/games/$id/dilemmas'
      preLoaderRoute: typeof GamesAuthenticatedIdDilemmasIndexLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/games/_authenticated/$id/star-system/$starSystemId': {
      id: '/games/_authenticated/$id/star-system/$starSystemId'
      path: '/star-system/$starSystemId'
      fullPath: '/games/$id/star-system/$starSystemId'
      preLoaderRoute: typeof GamesAuthenticatedIdStarSystemStarSystemIdLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/games/_authenticated/$id/ship-designs/new': {
      id: '/games/_authenticated/$id/ship-designs/new'
      path: '/new'
      fullPath: '/games/$id/ship-designs/new'
      preLoaderRoute: typeof GamesAuthenticatedIdShipDesignsNewLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdShipDesignsLazyRoute
    }
    '/games/_authenticated/$id/engagement/$engagementId': {
      id: '/games/_authenticated/$id/engagement/$engagementId'
      path: '/engagement/$engagementId'
      fullPath: '/games/$id/engagement/$engagementId'
      preLoaderRoute: typeof GamesAuthenticatedIdEngagementEngagementIdLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/games/_authenticated/$id/dilemmas/$dilemmaId': {
      id: '/games/_authenticated/$id/dilemmas/$dilemmaId'
      path: '/dilemmas/$dilemmaId'
      fullPath: '/games/$id/dilemmas/$dilemmaId'
      preLoaderRoute: typeof GamesAuthenticatedIdDilemmasDilemmaIdLazyRouteImport
      parentRoute: typeof GamesAuthenticatedIdLazyRoute
    }
    '/_dashboard/_authenticated/games/lobby/$id': {
      id: '/_dashboard/_authenticated/games/lobby/$id'
      path: '/games/lobby/$id'
      fullPath: '/games/lobby/$id'
      preLoaderRoute: typeof DashboardAuthenticatedGamesLobbyIdRouteImport
      parentRoute: typeof DashboardAuthenticatedRoute
    }
  }
}

interface DashboardAuthenticatedRouteChildren {
  DashboardAuthenticatedGamesIndexRoute: typeof DashboardAuthenticatedGamesIndexRoute
  DashboardAuthenticatedGamesLobbyIdRoute: typeof DashboardAuthenticatedGamesLobbyIdRoute
}

const DashboardAuthenticatedRouteChildren: DashboardAuthenticatedRouteChildren =
  {
    DashboardAuthenticatedGamesIndexRoute:
      DashboardAuthenticatedGamesIndexRoute,
    DashboardAuthenticatedGamesLobbyIdRoute:
      DashboardAuthenticatedGamesLobbyIdRoute,
  }

const DashboardAuthenticatedRouteWithChildren =
  DashboardAuthenticatedRoute._addFileChildren(
    DashboardAuthenticatedRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAuthenticatedRoute: typeof DashboardAuthenticatedRouteWithChildren
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardLearnRoute: typeof DashboardLearnRoute
  DashboardSigninRoute: typeof DashboardSigninRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuthenticatedRoute: DashboardAuthenticatedRouteWithChildren,
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardLearnRoute: DashboardLearnRoute,
  DashboardSigninRoute: DashboardSigninRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface GamesAuthenticatedIdShipDesignsLazyRouteChildren {
  GamesAuthenticatedIdShipDesignsNewLazyRoute: typeof GamesAuthenticatedIdShipDesignsNewLazyRoute
}

const GamesAuthenticatedIdShipDesignsLazyRouteChildren: GamesAuthenticatedIdShipDesignsLazyRouteChildren =
  {
    GamesAuthenticatedIdShipDesignsNewLazyRoute:
      GamesAuthenticatedIdShipDesignsNewLazyRoute,
  }

const GamesAuthenticatedIdShipDesignsLazyRouteWithChildren =
  GamesAuthenticatedIdShipDesignsLazyRoute._addFileChildren(
    GamesAuthenticatedIdShipDesignsLazyRouteChildren,
  )

interface GamesAuthenticatedIdLazyRouteChildren {
  GamesAuthenticatedIdShipDesignsLazyRoute: typeof GamesAuthenticatedIdShipDesignsLazyRouteWithChildren
  GamesAuthenticatedIdTurnReportsLazyRoute: typeof GamesAuthenticatedIdTurnReportsLazyRoute
  GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute: typeof GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute
  GamesAuthenticatedIdEngagementEngagementIdLazyRoute: typeof GamesAuthenticatedIdEngagementEngagementIdLazyRoute
  GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute: typeof GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute
  GamesAuthenticatedIdDilemmasIndexLazyRoute: typeof GamesAuthenticatedIdDilemmasIndexLazyRoute
}

const GamesAuthenticatedIdLazyRouteChildren: GamesAuthenticatedIdLazyRouteChildren =
  {
    GamesAuthenticatedIdShipDesignsLazyRoute:
      GamesAuthenticatedIdShipDesignsLazyRouteWithChildren,
    GamesAuthenticatedIdTurnReportsLazyRoute:
      GamesAuthenticatedIdTurnReportsLazyRoute,
    GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute:
      GamesAuthenticatedIdDilemmasDilemmaIdLazyRoute,
    GamesAuthenticatedIdEngagementEngagementIdLazyRoute:
      GamesAuthenticatedIdEngagementEngagementIdLazyRoute,
    GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute:
      GamesAuthenticatedIdStarSystemStarSystemIdLazyRoute,
    GamesAuthenticatedIdDilemmasIndexLazyRoute:
      GamesAuthenticatedIdDilemmasIndexLazyRoute,
  }

const GamesAuthenticatedIdLazyRouteWithChildren =
  GamesAuthenticatedIdLazyRoute._addFileChildren(
    GamesAuthenticatedIdLazyRouteChildren,
  )

interface GamesAuthenticatedRouteChildren {
  GamesAuthenticatedIdLazyRoute: typeof GamesAuthenticatedIdLazyRouteWithChildren
}

const GamesAuthenticatedRouteChildren: GamesAuthenticatedRouteChildren = {
  GamesAuthenticatedIdLazyRoute: GamesAuthenticatedIdLazyRouteWithChildren,
}

const GamesAuthenticatedRouteWithChildren =
  GamesAuthenticatedRoute._addFileChildren(GamesAuthenticatedRouteChildren)

interface GamesRouteChildren {
  GamesAuthenticatedRoute: typeof GamesAuthenticatedRouteWithChildren
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesAuthenticatedRoute: GamesAuthenticatedRouteWithChildren,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
