# Default values for space.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/rouby/space
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

secrets:
  JWT_SECRET: space-jwt
  APP_ORIGIN: "${APP_ORIGIN}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  className: "nginx"
  clusterIssuer: "letsencrypt-production"
  annotations: {}
  host: staging.space.aiacta.com
  tls:
    - secretName: space-tls
      hosts:
        - staging.space.aiacta.com

database:
  user: space
  password: space
  name: space

volumes: {}

volumeMounts: {}

persistentVolumeClaims: {}

nodeSelector: {}

tolerations: []

affinity: {}
