/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as DashboardSigninImport } from './routes/_dashboard/signin'
import { Route as DashboardLearnImport } from './routes/_dashboard/learn'
import { Route as DashboardGamesImport } from './routes/_dashboard/games'
import { Route as DashboardFeaturesImport } from './routes/_dashboard/features'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSigninRoute = DashboardSigninImport.update({
  path: '/signin',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLearnRoute = DashboardLearnImport.update({
  path: '/learn',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardGamesRoute = DashboardGamesImport.update({
  path: '/games',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFeaturesRoute = DashboardFeaturesImport.update({
  path: '/features',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/features': {
      id: '/_dashboard/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof DashboardFeaturesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/games': {
      id: '/_dashboard/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof DashboardGamesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/learn': {
      id: '/_dashboard/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof DashboardLearnImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/signin': {
      id: '/_dashboard/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof DashboardSigninImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardGamesRoute: typeof DashboardGamesRoute
  DashboardLearnRoute: typeof DashboardLearnRoute
  DashboardSigninRoute: typeof DashboardSigninRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardGamesRoute: DashboardGamesRoute,
  DashboardLearnRoute: DashboardLearnRoute,
  DashboardSigninRoute: DashboardSigninRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteWithChildren
  '/features': typeof DashboardFeaturesRoute
  '/games': typeof DashboardGamesRoute
  '/learn': typeof DashboardLearnRoute
  '/signin': typeof DashboardSigninRoute
  '/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/features': typeof DashboardFeaturesRoute
  '/games': typeof DashboardGamesRoute
  '/learn': typeof DashboardLearnRoute
  '/signin': typeof DashboardSigninRoute
  '/': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/features': typeof DashboardFeaturesRoute
  '/_dashboard/games': typeof DashboardGamesRoute
  '/_dashboard/learn': typeof DashboardLearnRoute
  '/_dashboard/signin': typeof DashboardSigninRoute
  '/_dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/features' | '/games' | '/learn' | '/signin' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/features' | '/games' | '/learn' | '/signin' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/features'
    | '/_dashboard/games'
    | '/_dashboard/learn'
    | '/_dashboard/signin'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/features",
        "/_dashboard/games",
        "/_dashboard/learn",
        "/_dashboard/signin",
        "/_dashboard/"
      ]
    },
    "/_dashboard/features": {
      "filePath": "_dashboard/features.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/games": {
      "filePath": "_dashboard/games.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/learn": {
      "filePath": "_dashboard/learn.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/signin": {
      "filePath": "_dashboard/signin.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
